{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "configmap.name" . }}
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
stringData:
{{- range $key, $value := .Values.configData }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }} 