{{- if .Values.svc.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-demo-chart.fullname" . }}
  labels:
    {{- include "k8s-demo-chart.labels" . | nindent 4 }}
    foo: baz
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "k8s-demo-chart.selectorLabels" . | nindent 4 }}
{{- end }} 