# https://www.reddit.com/r/ArgoCD/comments/1i7fr8y/comment/m8m54li/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button
# This is the secret for the test-cluster cluster in the argocd namespace
# It is used to connect to the cluster from the ArgoCD instance
# tlsClientConfig values are from kube config
apiVersion: v1
kind: Secret
metadata:
  name: test-cluster
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: test-cluster
  server: https://test-cluster-control-plane:6443
  config: |
    {
      "tlsClientConfig": {
        "caData": "<pulled from kube config>",
        "certData": "<pulled from kube config>",
        "keyData": "<pulled from kube config>",
        "serverName": "test-cluster-control-plane",
        "insecure": false
      }
    }
