# This is the secret for the kwok-cluster in the argocd namespace
# It is used to connect to the cluster from the ArgoCD instance
# tlsClientConfig values are from kube config
apiVersion: v1
kind: Secret
metadata:
  name: kwok-cluster
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: kwok-cluster
  server: https://kwok-cluster-control-plane:6443
  config: |
    {
      "tlsClientConfig": {
        "caData": "<pulled from kube config>",
        "certData": "<pulled from kube config>",
        "keyData": "<pulled from kube config>",
        "serverName": "kwok-cluster-control-plane",
        "insecure": false
      }
    } 
